- examples/bubbletea/main.go
- examples/git/main.go
change the examples to use graceful shutdown, as its usually a good thing.
> docs: examples using graceful shutdown

- README.md
This adds @caarlos0’s pro tip to the README.
> Add tip about UserKnownHostsFile setting in local dev

- accesscontrol/accesscontrol_test.go
- activeterm/activeterm_test.go
- logging/logging_test.go
- testsession/testsession.go
- testsession/testsession_test.go
simplify test code and ensure everything is closed.
> test: refactor testing code a bit

- git/git.go
* filepath.Clean repo path
* Only use base element
* Return invalid repo error if not found
Fixes #23
> Sanitize repo file path

- .gitignore
- git/git_test.go
added tests for the git middleware
extracted from #28
> test: add tests for git middleware

- recover/recover.go
- recover/recover_test.go
recover middleware wraps other middlewares and recover from panics
> feat: add recover middleware

- bubbletea/tea.go
- go.mod
- go.sum
this will restore the terminal if the program crashes, should be a no-op
if the program exits correctly
> feat(tea): kill and restore terminal when program exits

- README.md
Finally got time to try out all the charm tools, it's amazing folks, well done!
> docs: add ssh-warm-welcome

- examples/bubbletea/main.go
- examples/bubbleteaprogram/main.go
- examples/simple/main.go
using the new print functions in the examples.
> docs: use wish.Println on examples

- README.md
my attempt at better explaining ssh apps :)
> docs: explain ssh apps

- go.mod
- go.sum
- ratelimiter/ratelimiter.go
- ratelimiter/ratelimiter_test.go
this impl is thread safe and also has no deps.
> feat: use a thread safe lru cache

- logging/logging.go
Logging middleware now can use a custom logger.
> feat(logging): custom logger

- wish.go
- wish_test.go
uses a writer that wraps the if statement, and added tests
> refactor: crlf writer

- git/git.go
- git/git_test.go
Allow using nested repos similar to GitHub/Gitlab and the likes. `<user>/<repo>.git` but also allow repos living in the root path.
This won't allow more than one level of nesting i.e. `<parent1>/<parent2>/<repo.git>` is not allowed.
Fixes: https://github.com/charmbracelet/soft-serve/issues/120
> fix(git): allow user repos

- README.md
tried to keep it short and simple, let me know if you think I should add more to it.
closes #97
> docs: document a little bit how wish works

- .github/workflows/goreleaser.yml
- .goreleaser.yml
announce releases 
refs https://github.com/charmbracelet/meta/pull/63
> chore: announce patches

- examples/go.mod
- examples/go.sum
- go.mod
- go.sum
> feat: update lipgloss

- .github/dependabot.yml
also added examples update config
> build: group dependabot updates

- git/git.go
> feat: make EnsureRepo public

- examples/forward/main.go
- examples/go.mod
- examples/go.sum
> docs: add an example of reverse proxy

- examples/bubbletea/main.go
- examples/pty/main.go
> docs: HasDarkBackground() in examples

- bubbletea/tea_unix.go
- examples/go.mod
- examples/go.sum
- go.mod
- go.sum
use our new term lib to query the bg, set it into the lipgloss renderer so it works with everything.
refs #262
> feat: background color detection

- examples/bubbletea/main.go
- examples/go.mod
- examples/go.sum
- go.mod
- go.sum
for some `TERM` values, termenv already knows its a truecolor capable term.
this updates termenv and add it to the bubbletea example.
> feat: update termenv, improve truecolor detection
