accesscontrol/accesscontrol.go, accesscontrol/accesscontrol_test.go, activeterm/activeterm.go, activeterm/activeterm_test.go
say what's wrong instead of just exiting 1
=> fix: improve accesscontrol and activeterm middlewares

examples/bubbletea/main.go, examples/git/main.go
refs #16
using `Close` directly kills connections and may leave the terminal may not be restored
=> fix: examples showing how to properly shutdown the server

bubbletea/tea.go
this fixes a lint issue and also makes usage a bit nicer, instead of 
```go
bubbletea.BubbleTeaHandler()
```
you can use
```go
bubbletea.Handler()
```
directly, which reads a bit less repetitive.
This change is backwards-compatible with previous versions. 🙏
=> refactor: rename BubbleTeaHandler to Handler

accesscontrol/accesscontrol.go, activeterm/activeterm.go, bubbletea/tea.go, git/git.go, testsession/testsession.go
fixes/ignores everything golangci-lint is complaining about.
=> refactor: fix all linter issues

git/git.go
we don't need to worry about executing other middleware if git
middleware picks up a receive/upload command
=> feat: exit session after handling git commands

bubbletea/tea.go, examples/bubbleteaprogram/main.go
This allows passing a program handler that returns tea.Program to allow
for more advanced use cases such as using p.Send() to send messages to
tea.Program.
Fixes: https://github.com/charmbracelet/wish/issues/37
=> feat: add bubbletea program middleware

.gitignore, examples/simple/main.go
this adds a simple wish app example, with no bubbletea or anything else,
so it can be easily copied and extended.
=> docs: add a simple wish app example

README.md, examples/bubbletea/main.go, examples/bubbleteaprogram/main.go, examples/git/main.go, examples/simple/main.go, options.go
- some linter issues fixed
- minor docs/readme improvements
=> docs: several example improvements

.gitignore, examples/identity/main.go
An simple example showing how to handle user identity.
Signed-off-by: Carlos A Becker <caarlos0@users.noreply.github.com>
=> docs: example showing how to handle user identity

examples/simple/main.go, wish.go
It seems that forcing an early `session.Exit` might cause formatting issues if a `\r` is not printed as well.
I'm not sure why this happens, but this seems to fix it.
Screenshot of the problem happening:
=> fix: EOL when force-closing the connection

git/git.go, git/git_test.go
instead of running git-upload-pack/git-receive-pack use git [command]
some systems don't have those commands aliased to git for example
git-for-windows doesn't have those aliases
Fixes: https://github.com/charmbracelet/soft-serve/issues/115
=> fix: use the git binary to run upload/receive commands

scp/scp.go
If you wanna serve scp requests and other commands as well in the same server, when a scp request happens, nothing else should be executed after that.
if, say, we run scp, and then handler over to a cobra app, it'll print stuff to stdout, which will make the scp command fail with something like:
```
protocol error: expected control record
```
if the command is not scp, it will still proceed to then next item in the chain, so that should not be an issue.
=> fix(scp): do not proceed chain

bubbletea/tea.go
we never really break out of that for loop, so, the goroutine would keep running there even long after the program that launched it finished.
this fixes it.
=> fix: goroutine leak

.github/workflows/build.yml, .github/workflows/lint.yml, go.mod, go.sum, ratelimiter/ratelimiter.go
=> feat: update golang-lru to v2

options.go, options_test.go
this will always read the authorized keys file instead of caching it, bringing the way it works closer to openssh.
as a downside, if the file is big, it might take a while. We could cache it, but I think it should be fine as is.
#82
=> feat: always read the authorized keys file

.github/workflows/build.yml
we can measure code coverage only once for linux and latest go, should be fine.
=> chore: avoid uneeded runs of codecov workflow

.golangci.yml, examples/bubbletea/main.go, examples/bubbleteaprogram/main.go, examples/cobra/main.go, examples/git/main.go, examples/go.mod, examples/identity/main.go, examples/scp/main.go, examples/simple/main.go
this prevents leaking "the beginning" of another log line, as well as "wrong" errors (server closing is fine :))
=> fix: properly handle server closed on examples

examples/bubbletea/main.go, examples/bubbleteaprogram/main.go, examples/cobra/main.go, examples/git/main.go, examples/identity/main.go, examples/scp/main.go, examples/simple/main.go
Without this change, if the server fails to start, the program will hang waiting for a signal on `done` before properly exiting.
=> fix(examples): properly shut down if failed to start

bubbletea/tea.go
Set the global color profile once out of the middleware. We don't need to set the value every time the middleware is called. This also adds a comment about the behavior.
=> fix(tea): set the color profile once

elapsed/elapsed.go
You can actually called elapsed as many times as you'd like, anywhere in the chain. In order to be most useful, you should probably call it at the end.
=> Improve Elapsed Documentation

cmd.go, cmd_darwin.go, cmd_test.go, cmd_unix.go, cmd_windows.go, go.mod
dirty fix to "inappropriate ioctl for device" on macOS.
It seems that macOS kills the slave pty once `exec.Cmd` finishes... so we need to create a new PTY just to run said program in order to avoid that problem.
Need to test, but this might make things possible on windows, too.
=> fix: create a new pty for exec.Cmd

wish.go
Golang SSH will set a default version when this is empty, using "OpenSSH_7.6p1" is misleading and causes SSH clients to misidentify the server version.
Reference: https://pkg.go.dev/golang.org/x/crypto/ssh#:~:text=//%20%22SSH%2D2.0%2D%22.-,ServerVersion,-string%0A%0A%09//%20BannerCallback%2C%20if
Fixes: https://github.com/charmbracelet/soft-serve/issues/485
=> fix: remove ssh server version

logging/logging.go, logging/logging_test.go
Supports logging with charmbracelet/log in a structured format, especially useful with JSON logs.
Also added the client version to the logs
=> feat: logging.StructuredMiddleware

examples/README.md
Hey, just noticed one of the links in `./examples/README.md` was pointing to the wrong directory.
=> docs: fix broken link in examples readme

bubbletea/tea_unix.go, go.mod
=> fix: put pty slave in raw mode before querying

bubbletea/tea.go
We only force the color profile if the requested session is a PTY. We also print warning messages to the client's stderr if we force a color profile.
Fixes: https://github.com/charmbracelet/soft-serve/issues/683
=> fix(tea): do not force color profile if session is not a PTY

bubbletea/tea.go
suspend would actually suspend the server instead of the connection.
ignoring suspend msgs, then users can type tilde-ctrl+z and it works as expected.
=> feat(v2): prevent suspending bubbletea
